version: '3.1'
services:
  app:
    container_name: app-testnovae
    image: app-testnovae
    build: ./
    ports:
      - "8081:8081"
    depends_on:
      - dbpostgresql
  dbpostgresql:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=testnovae